// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import "forge-std/Test.sol";
import "forge-std/console.sol";
import { Ed25519Verifier } from "../src/lib/Ed25519Verifier.sol";
import { SCL_EIP6565 } from "@solidity/lib/libSCL_EIP6565.sol";
import "@solidity/lib/libSCL_eddsaUtils.sol";

/**
 * @title Ed25519 End-to-End Cross-Verification Test
 * @notice Verifies that a signature generated by @noble/ed25519 in JS
 *         can be verified on-chain by SCL's Verify_LE via our Ed25519Verifier.
 */
contract Ed25519E2E is Test {
    // RFC 8032 vector 2 secret (used to generate known keypair)
    uint256 constant SECRET_2 = 0x4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb;

    // Challenge hash generated by JS: keccak256(abi.encodePacked(
    //   "self-agent-id:register-ed25519:",
    //   address(0), uint256(31337), address(0x1111...1111), uint256(0)
    // ))
    bytes32 constant CHALLENGE_HASH = 0xd536b8dc2c02a056000a899c6812f0a6431aed4992f19075aea13a803e111652;

    // Signature generated by @noble/ed25519 over the above challenge hash
    // These are in LE format (native Ed25519)
    uint256 constant SIG_R = 0x010a463562451f03d37cbf5d51b3a798e69b56ac0643a1802e03cecb59446d99;
    uint256 constant SIG_S = 0x524870a6e28eaef00a8bee48a2bc237b5a0b3afa89965be6eed0a1229a30f507;

    function test_e2e_jsSignatureVerifiesOnChain() public view {
        // Compute extKpub from the known secret (same as JS computation)
        uint256[5] memory extKpub;
        (extKpub,) = SCL_EIP6565_UTILS.SetKey(SECRET_2);

        // The message for Ed25519 Verify_LE is the raw 32-byte challenge hash
        // passed as a string (bytes)
        string memory message = string(abi.encodePacked(CHALLENGE_HASH));

        // Verify using our Ed25519Verifier wrapper
        bool valid = Ed25519Verifier.verify(message, SIG_R, SIG_S, extKpub);
        assertTrue(valid, "JS-generated Ed25519 signature should verify on-chain");
    }

    function test_e2e_challengeHashMatchesContract() public view {
        // Reconstruct the challenge hash the same way the contract does
        address humanAddress = address(0);
        uint256 chainId = 31337;
        address registry = address(0x1111111111111111111111111111111111111111);
        uint256 nonce = 0;

        bytes32 reconstructed = keccak256(abi.encodePacked(
            "self-agent-id:register-ed25519:",
            humanAddress,
            chainId,
            registry,
            nonce
        ));

        assertEq(reconstructed, CHALLENGE_HASH, "Challenge hash mismatch between JS and Solidity");
    }

    function test_e2e_derivedAddressMatches() public pure {
        bytes32 pubkey = bytes32(0x3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c);
        address derived = Ed25519Verifier.deriveAddress(pubkey);
        // This must match what the JS deriveEd25519Address produces
        address expected = address(uint160(uint256(keccak256(abi.encodePacked(pubkey)))));
        assertEq(derived, expected, "Derived address mismatch");
    }

    function test_e2e_invalidSignatureRejected() public view {
        uint256[5] memory extKpub;
        (extKpub,) = SCL_EIP6565_UTILS.SetKey(SECRET_2);

        string memory message = string(abi.encodePacked(CHALLENGE_HASH));

        // Corrupt signature S
        bool valid = Ed25519Verifier.verify(message, SIG_R, SIG_S + 1, extKpub);
        assertFalse(valid, "Corrupted signature should not verify");
    }
}
